services:
  - type: web
    name: resume-validator
    runtime: python
    buildCommand: pip install --use-deprecated=legacy-resolver -r requirements.txt
    startCommand: streamlit run main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
