services:
  - type: web
    name: resume-validator
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port=$PORT --server.enableCORS=false
    envVars:
      - key: PORT
        value: 10000

