services:
  - type: web
    name: resume-validator
    runtime: docker  # <== THIS IS CRITICAL
    plan: free
    dockerfilePath: DOCKERFILE
    envVars:
      - key: PORT
        value: 10000

